@echo off
setlocal
REM 
REM Set STST_HOME to the folder where stst.zip was extracted to.
REM Rename to stst.bat and copy to somewhere on your path or add this folder to your path.
REM Make sure the java command is on the path or JAVA_HOME is defined.
REM
set STST_HOME=<home>

set JAVA_CMD=java
if not "%JAVA_HOME%"=="" set JAVA_CMD="%JAVA_HOME%\bin\java"
set CP=%STST_HOME%\lib\stst.jar;%STST_HOME%\lib\ST-4.0.8.jar
%JAVA_CMD% -cp %CP% jjs.stst.STStandaloneTool %*
